### PR TITLE
Update: Peer2Peer Demo Update

### PR DESCRIPTION
**Pull request by Raxnam**
Pushing P2P demo scene update

README file added

reworked some of the networking code to accommodate non-text data, there's probably a cleaner way to do this with just casting, but this works for now

Added files:
Particle Prefab
Particle System Prefab
Particle Lifetimer script - controls particles movement
Particle Manager script - spawns particle system
Particle System script - manages spawning individual particles and "physics" attached

Changed Files:
Peer2Peer Scene - added a button component to the Peer2Peer UI window allowing for click events on it as well as adding the particle manager to the same component to allow for spawning of particle systems within the buttons local space

Peer2PeerManager.cs - Added functionality to allow for non-text data to be sent, this is pretty crude, and could be done better with some casting, something I'd like to get to at some point
Some of the networking code in this got reorganized to allow for as little repeat code as needed while maintaining the same flow

Peer2PeerMenu.cs - Changed the send message functionality to fit the slightly more generic function in the manager, as well as added the function to call on click to generate the particle message data

### CODE REVIEW

**Comment by andrew-hirata-playeveryware** [comment]
It looks like this change was made off of `stable` instead of from `development`. While unfortunately counter-intuitive, new features are to be made from the `development` branch, not from the `stable` branch.  I think that's also what's causing those merge conflicts above. This should be resolvable by either doing a rebase to move the branch so it's based on `development` or cherry-picking the changes to a new branch based on `development`. I also noticed that the commit messages don't follow the current [standard](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/standards.md) for commit messages

**Comment by Raxnam** [comment]
> It looks like this change was made off of `stable` instead of from `development`. While unfortunately counter-intuitive, new features are to be made from the `development` branch, not from the `stable` branch. I think that's also what's causing those merge conflicts above. This should be resolvable by either doing a rebase to move the branch so it's based on `development` or cherry-picking the changes to a new branch based on `development`. I also noticed that the commit messages don't follow the current [standard](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/standards.md) for commit messages

Alright, thanks I'll get that sorted out and make a new pull request once it's all sorted out

**Comment by andrew-hirata-playeveryware** [comment]
It looks like your rebase rewrote history of 10 commits before your actual changes such that you're the author of it those changes.

**Comment by Raxnam** [comment]
I'm not too familiar with rebasing so It didn't go as planned; its amended me to be the author for any of the commits it thought there were conflicts for. 

I'm just going to work off a new branch, I can keep it much cleaner that way, and I'm more familiar with it.

**Pull request closed without merging**
