### PR TITLE
Fixed SimplePrintCallback breaking on some Language Cultures (i.e. Thai)

### PR DESCRIPTION
**Pull request by GiovanniFrigo**
Proposed fix for issue #467

### CODE REVIEW

**Review by paulhazen — APPROVED** [review]
Good call, there are probably some other places where we could do this, but this is a good start! Thanks for contributing! :)

**Review by andrew-hirata-playeveryware — APPROVED** [review]

**Review by paulhazen — CHANGES_REQUESTED** [review]
Hey, forgot one thing - we keep things in `development` for a while before merging with `stable`. Can you please change which branch you've opened the pull request for?

**Comment by paulhazen** [comment]
Since the change was small, I replicated it, but from the base of `development`, and requesting merging into `development`. New PR: https://github.com/PlayEveryWare/eos_plugin_for_unity/pull/470

**Comment by GiovanniFrigo** [comment]
Fair enough! Thank you @paulhazen

**Pull request closed without merging**
